### ISSUE TITLE
Update readme to latest beta 

### ISSUE THREAD

**Issue by thclark** [octue/check-semantic-version#15]
## Feature request

Readme instructs on installing an old beta, and doesn't show the ability to configure breaking change versions.

Should include something like:
```

      - name: Check version
        uses: octue/check-semantic-version@1.0.0.beta-9
        with:
          path: package.json
          breaking_change_indicated_by: major
```
