### ISSUE TITLE
Remove need for mkver.conf

### ISSUE THREAD

**Issue by thclark** [octue/check-semantic-version#7]
## Feature request

Allow inline generation of a mkver.conf file, so that if it's missing from the repo we don't need to build it.

### Use Case

I'd rather not maintain mkver.conf across every single repository, when there's basically only one thing we ever change, which is increment majoo vs minor on breaking change.

if we had a flag in the yaml:
```
steps:
- uses: octue/check-semantic-version@1.0.0.beta-2
  with:
    path: setup.py
    increment_major_on_break: False  # default true
```

Other than that we use our default mkver.conf (unless one is found, in which case use that) then this action would work out of the box on a new repository.
